fix github pages issues

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,13 +16,16 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: 18 # Use a specific Node.js version
+          node-version: 18
 
       - name: Install dependencies
-        run: npm ci --legacy-peer-deps # Add the --legacy-peer-deps flag
+        run: npm ci --legacy-peer-deps
 
       - name: Build project
         run: npm run build
+
+      - name: Verify index.html
+        run: test -f ./out/index.html || (echo "index.html not found in ./out" && exit 1)
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
